### ISSUE TITLE
example-robot-data is required dependency even without tests

### ISSUE THREAD

**Issue by pFernbach** [Gepetto/aig#18]
Example-robot-data is only required for the unit tests, it's correctly set as test_depend in the package.xml but it's always required in the CMakeLists.txt : 
https://github.com/Gepetto/aig/blob/16d51618674c79e3a166a7f6f7963de299275fac/CMakeLists.txt#L42

**Comment by MaximilienNaveau** [comment]
We would benefit from a release for the packaging of @pFernbach I guess.
We have a pending PR which need more work that could also be release.
Question is, do we wait the pending PR for a new release?

**Comment by pFernbach** [comment]
Oh I didn't check on the devel branch, sorry. I can wait a couple of days for this. I will take a look at the pending PR
