### ISSUE TITLE
Biped_ig depend on example robot data

### ISSUE THREAD

**Issue by pFernbach** [Gepetto/aig#19]
This part of the sources depend on example robot data : 
https://github.com/Gepetto/aig/blob/16d51618674c79e3a166a7f6f7963de299275fac/src/biped_ig.cpp#L17-L41 @NahuelVilla 

I think it should be remove from here as it's very specific and does not fit the rest of the package. I think the dependency to example robot data should be only for the tests.

**Comment by NahuelVilla** [comment]
Ok, we discussed that function with @MaximilienNaveau recently. I guess, we agree with you, but we left it there to keep a simple initialization of the biped_ig. Without that function, the whole setting should be written each time that `aig` is instantiated.

Maybe, we can make another script `tools.cpp` which would depend on example robot data to implement this kind of helpers.
WDYT?

**Comment by MaximilienNaveau** [comment]
Let me have a quick look at the code to see if I can find a compromise.
