### ISSUE TITLE
devel is broken

### ISSUE THREAD

**Issue by nim65s** [Gepetto/aig#31]
Hi,

According to the [CI](https://gitlab.laas.fr/gepetto/aig/-/jobs/177496), the current devel branch is not working in Debug mode:
```
/root/robotpkg/wip/aig/work/aig-1.1.0/tests/test_biped_ig.cpp(249): error: in "BOOST_TEST_MODULE/test_compute_dynamics": check biped_ig.getAM().isMuchSmallerThan(1) has failed
```

@MaximilienNaveau : why did you merge #28  ? Can this be fixed or should I revert ?

**Comment by MaximilienNaveau** [comment]
I will have a look

**Comment by MaximilienNaveau** [comment]
arf indeed it's reproducible, I will try to find the issue.
